version: '2'

services:
  elasticsearch:
    restart: always
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300

  web:
    build: .
    restart: always
    ports:
    - "5000:5000"
    volumes:
    - .:/app
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    environment:
    - db_host=elasticsearch
    - db_port=9200

